---
title: "Glossary"
output: html_document
---

## Appendix 1 - Definitions

### Project and Campaign terms

#### Project

- Contains one to multiple [<u>Campaign</u>](#campaign)s with a shared purpose/objective (e.g. monitoring of a Marine Park, a bioregional study).

- [<u>Project</u>](#_1a4bxgjenifp) is a unique identifier and the name should be carefully chosen (e.g. “MarineParkMonitoring” is not a good [<u>Project</u>](#_1a4bxgjenifp) name but “Houtman Abrolhos Reef Observation Areas long-term monitoring” is a great [<u>Project</u>](#_1a4bxgjenifp) name)

- Sampling and image analysis methods are generally standardised within a [<u>Project</u>](#_1a4bxgjenifp) but sampling method for each [<u>Campaign</u>](#campaign) can be different (e.g. one [<u>Campaign</u>](#campaign) could use DOV whereas another [<u>Campaign</u>](#campaign) could use BRUV or UVC).

#### Scale

- The geographic extent at which the dataset, Project, or [<u>sample</u>](#sample) is relevant or intended to be applied (e.g. International, National, Regional, or Local).

#### Type

- The category that best describes the primary context or intended use of the dataset or project.

- Cultural, Academic, Industry or Management

#### Campaign

- A discrete set (temporal and spatial) of [<u>samples</u>](#sample).

- All [<u>samples</u>](#sample) within a [<u>Campaign</u>](#campaign) use the same sampling and image analysis [<u>methods</u>](#method).

#### CampaignID

- A unique identifier for a [<u>Campaign</u>](#campaign) made up of YYYY-MM_Campaign_Method.

- The date is the start date of the [<u>Campaign</u>](#campaign) (e.g. 2023-12_Rottnest-Island-Marine-Parks_stereo-BRUVs).

#### Annotation Set

- A collection of annotations from a defined set of [<u>samples</u>](#sample) within a [<u>Campaign</u>](#campaign) , grouped together as a single dataset.

#### Annotation Metadata

- The descriptive information associated with an [<u>Annotation Set</u>](#annotation-set) that provides context for the annotations and information on how the [<u>samples</u>](#sample) were annotated.

- For example levels of identification and software used to annotate.

#### Method

- Any sampling [<u>method</u>](#method) (e.g. stereo-BRUVs, stereo-DOVs, UVC). Contact Administrator to create a new Method.  
  Defined in the “[<u>Methods</u>](#method)” tab.

#### Sample

- Single observational unit (e.g. a BRUV deployment or DOV transect).  
  Must match exactly across sample metadata and any annotation/EMObs files.  
  Defined by opcode only, period only, or opcode + period.

<!-- -->

- 

#### Vocabularies

- The approved controlled vocabularies used in EMObs to standardise annotation of fish, benthic biota, and substrates.

- These ensure annotations are applied consistently and can be compared across [<u>projects</u>](#projects) and datasets.

### Synthesis terms

#### Synthesis/Syntheses

- Combines information from multiple [<u>Campaigns</u>](#campaign) with the same [<u>method</u>](#method) from multiple locations and/or multiple times.

#### Scale

- The geographic extent at which the [<u>Synthesis</u>](#synthesis) is relevant or intended to be applied

- International, National, Regional or Local

#### Type

- The category that best describes the primary context or intended use of the [<u>Synthesis</u>](#synthesis).

- Cultural, Academic, Industry or Management

### User Access and Sharing terms

#### Custodian

- A [<u>user</u>](#user) who creates a [<u>Project</u>](#project), and the [<u>Campaigns</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.watfbpgrrufl) within it, is the Custodian.

- Only the Custodian can upload [<u>Campaigns</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.watfbpgrrufl) to that [<u>Project</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.l7x8x11101qp) and share the [<u>Campaigns</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.watfbpgrrufl) or the entire [<u>Project</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.l7x8x11101qp) with other [<u>Users</u>](#user).

- The Custodian should be the person within the institution with a long term interest in the data and the person who should be contacted if another user wants to use the data (e.g. will more likely be a Principal Investigator than a research assistant).

#### Projects

- [<u>Projects</u>](#project) are typically to organise data within a research group/organisation (e.g. Monitoring of a specific marine park by the NSW Department of Primary Industries).

- Sharing a [<u>Project</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.l7x8x11101qp) with another [<u>User</u>](#user) allows them to query all [<u>Campaigns</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.watfbpgrrufl) within it.

#### Synthesis

- A [<u>Synthesis</u>](http://synthesis/Syntheses) is designed for sharing of data from multiple [<u>Campaigns</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.watfbpgrrufl) for data analysis.

- The User who created the [<u>Synthesis</u>](http://synthesis/Syntheses) is the Custodian of the [<u>Synthesis</u>](http://synthesis/Syntheses).

- Only the Custodian can share the [<u>Synthesis</u>](http://synthesis/Syntheses) with other Users.

#### User

- User registration and login provides secure access to the [<u>Campaigns</u>](https://docs.google.com/document/d/1yU-zrEIwBN1B-w-rnwxRlZ8rEioJ37bxk7l5LkXhgoM/edit?userstoinvite=annika.leunig%40marineecology.io&sharingaction=manageaccess&role=reader&tab=t.0#heading=h.watfbpgrrufl) and [<u>Projects</u>](#project) you upload and that are shared with you.

## Appendix 2 - How to download and summarise annotation data

- Coming soon…

